// create a proto file
syntax = "proto3";
package pb;
option go_package = "internal/pb";

message Blank{}

message Category {
    string id = 1;
    string name = 2;
    optional string description = 3;
}

message CreateCategoryRequest {
    string name = 1;
    optional string description = 2;
}

message GetCategoryRequest {
    string id = 1;
}

message UpdateCategoryRequest {
    string id = 1;
    string name = 2;
    optional string description = 3;
}

message DeleteCategoryRequest {
    string id = 1;
}

message CategoryList {
    repeated Category categories = 1;
}

message ListCategoriesByNameRequest {
    string name = 1;
}

service CategoryService {
    rpc CreateCategory(CreateCategoryRequest) returns (Category);
    rpc GetCategory(GetCategoryRequest) returns (Category);
    rpc UpdateCategory(UpdateCategoryRequest) returns (Category);
    rpc DeleteCategory(DeleteCategoryRequest) returns (Category);
    rpc ListCategories(Blank) returns (CategoryList);
    rpc ListCategoriesByName(ListCategoriesByNameRequest) returns (CategoryList);
}
